### ISSUE TITLE
RSS Memory collection is failing due too many open files

### ISSUE THREAD

**Issue by davidfrickert** [davidfrickert/FunctionRunner#29]
It seems that metrics collection is running too often and causing problems in the RSS memory collection phase.

**Stacktrace**
```
16:06:48.074 [Thread-1] ERROR p.i.p.metrics.MemoryHelper - Couldn't fetch RSS memory!
java.io.IOException: Cannot run program "ps": error=24, Too many open files
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at java.lang.Runtime.exec(Runtime.java:592)
        at java.lang.Runtime.exec(Runtime.java:416)
        at java.lang.Runtime.exec(Runtime.java:313)
        at pt.ist.photon_graal.metrics.MemoryHelper.rssMemory(MemoryHelper.java:23)
        at io.micrometer.core.instrument.internal.DefaultGauge.value(DefaultGauge.java:54)
        at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$newGauge$5(PrometheusMeterRegistry.java:280)
        at io.micrometer.prometheus.MicrometerCollector.collect(MicrometerCollector.java:70)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:207)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.<init>(CollectorRegistry.java:171)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.<init>(CollectorRegistry.java:192)
        at io.prometheus.client.CollectorRegistry.metricFamilySamples(CollectorRegistry.java:147)
        at io.prometheus.client.exporter.PushGateway.doRequest(PushGateway.java:250)
        at io.prometheus.client.exporter.PushGateway.pushAdd(PushGateway.java:158)
        at pt.ist.photon_graal.metrics.MetricsSupport.push(MetricsSupport.java:56)
        at pt.ist.photon_graal.metrics.MetricsPusher.run(MetricsPusher.java:21)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.io.IOException: error=24, Too many open files
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_io_IOException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
        at java.lang.ProcessImpl.forkAndExec(ProcessImpl.java)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)

```
And also, after:

```
java.lang.NumberFormatException: For input string: ""
        at java.lang.Long.parseLong(Long.java:702)
        at java.lang.Long.parseLong(Long.java:817)
        at pt.ist.photon_graal.metrics.MemoryHelper.rssMemory(MemoryHelper.java:36)
        at io.micrometer.core.instrument.internal.DefaultGauge.value(DefaultGauge.java:54)
        at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$newGauge$5(PrometheusMeterRegistry.java:280)
        at io.micrometer.prometheus.MicrometerCollector.collect(MicrometerCollector.java:70)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:207)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.<init>(CollectorRegistry.java:171)
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.<init>(CollectorRegistry.java:192)
        at io.prometheus.client.CollectorRegistry.metricFamilySamples(CollectorRegistry.java:147)
        at io.prometheus.client.exporter.PushGateway.doRequest(PushGateway.java:250)
        at io.prometheus.client.exporter.PushGateway.pushAdd(PushGateway.java:158)
        at pt.ist.photon_graal.metrics.MetricsSupport.push(MetricsSupport.java:56)
        at pt.ist.photon_graal.metrics.MetricsPusher.run(MetricsPusher.java:21)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

**Comment by davidfrickert** [comment]
So what seems to be happening is some sort of stream leak, but couldn't find the culprit by looking at the code. Temporarily fixed by using Isolate Pools which greatly reduce the destruction of Isolates during high load.
